### ISSUE TITLE
Unexpected semver breaking: after 0.6.3, `im::Vector` is no longer considered an "indirection" for the purposes of recursive types.

### ISSUE THREAD

**Issue by nullchinchilla** [bodil/sized-chunks#16]
This structure compiles on 0.6.2 but not 0.6.3:

```rust
pub enum Value {
    Int(U256),
    Bytes(im::Vector<u8>),
    Vector(im::Vector<Value>),
}
```

On 0.6.3 this says

```
recursive type `Value` has infinite size
```

Did 0.6.3 add some sort of small-vector optimization?

**Comment by kornelski** [comment]
@vorner could this be because of change from `PhantomData` to `[A; 0]`? 9a2e7891f0dc9f4fa411c81a86b8c80f3ce6bf80

**Comment by vorner** [comment]
That sounds possible :thinking:… It's likely PhantomData acts differently than an array, even 0-element one, in this regard. But I'm not sure what to do about it. Any other idea how to enforce a large-enough alignment for A without this? Or, alternatively, one could decide to simply avoid doing the inline-storing for types with large alignment.

To @nullchinchilla … there always was a small-vector optimization, except it was invisible to the compiler.

**Comment by kornelski** [comment]
I don't know if *not* storing elements with larger alignment isn't another breaking change. After all, it'd be an inline array that isn't inline.

Maybe use `read_unaligned`?

**Comment by vorner** [comment]
That read_unaligned doesn't sound nice either :-(. Types with larger-than-usize alignment exist mostly for two reasons:

* Avoiding false sharing in multithreaded environments
* SIMD

Both of these du the alignment because of performance. In both cases, the performance would suffer because of that read_unaligned.

And things like `Deref` and `DerefMut` wouldn't work with that anyway.

**Comment by kornelski** [comment]
So maybe u64/f64 alignment on all platforms? (usize is too small on 32-bit)

**Comment by vorner** [comment]
There's no upper limit on what an arbitrary type's alignment may be. Misaligning it is UB. Accessing unaligned vectors often manifests as segfaults on modern x86_64. This one aligns for 256 bits: https://doc.rust-lang.org/core/arch/x86_64/struct.__m256i.html.

The fake sharing wrappers have also large alignments: https://docs.rs/crossbeam-utils/0.8.1/src/crossbeam_utils/cache_padded.rs.html#71

**Comment by kornelski** [comment]
I've meant supporting alignments up to u64, and not storing inline anything with larger alignment.

**Comment by kornelski** [comment]
I've realized that 0.6.2 was unsound with >usize alignments, so we don't need to support larger alignments.

**Comment by kornelski** [comment]
Oh, maybe add a third defaulted type arg for the alignment?

```
InlineArray<T, C, A = usize> {}
…
InlineArray<T, C, __m256i>
```

**Comment by vorner** [comment]
> Oh, maybe add a third defaulted type arg for the alignment?

How would that help?

I think the options are (if we need to return to the support of the indirection and see no other way how to „extract“ the alignment from the type):
* Decide on upper alignment bound and store stuff with bigger ones out of line. That should be fine with things bigger than u64, as while possible, they are likely rare and also unlikely to be stored in this. If I do the cache padding, I usually put them to some thread-local thing. If I do SIMD, there's _a lot_ of data (otherwise there's not much reason to do SIMD) and won't fit inline anyway.
* Do the alignment „manually“ ‒ compute the offset where the inline data start. That can waste some amount of space and will make it less predictable how many elements fit.
* Align to `sizeof::<InlineArray>`. Bigger things will not fit and things that have bigger alignment than size are broken anyway and we can round them up to „bigger“ and store out of line. But that might waste some space in the „usual“ case?

**Comment by kornelski** [comment]
User could put a simpler, non-recursive type in the extra align arg to align the whole struct with `[A; 0]` trick. alignof A >= alignof T can be asserted to make it sound.

I don't think it's safe to do alignment "manually", because Rust can move the whole struct to differently aligned address, invalidating manual padding.

**Comment by vorner** [comment]
> User could put a simpler, non-recursive type in the extra align arg to align the whole struct with [A; 0] trick. alignof A >= alignof T can be asserted to make it sound.

I think the main use case for this type is still being used as part of `im` (which is even the reporter's motivation, if I'm right). And I don't think `im::Vector` would want to have such thing in their public API.
